### ISSUE TITLE
Get less->css as string instead of auto-adding to page?

### ISSUE THREAD

**Issue by gobengo** [guybedford/require-less#64]
Hey, I currently use require-less in quite a few projects, usually for webapps that are embedded natively on arbitrary pages.

I would like to continue writing in LESS, but be able to get the compiled CSS as a string instead of having it auto-added to the page. I then intend to use something like rework to prefix all the selectors with a uid.
https://github.com/reworkcss/rework#prefixselectorsstring

Is there a way to use require-less to get a CSS string in my module? Currently I am returned undefined :(

**Comment by Obooman** [comment]
I'll close this issue for being inactive for a long time, feel free to comment if YOU needs this.
