### ISSUE TITLE
Upgrade to less version 2

### ISSUE THREAD

**Issue by larsthorup** [guybedford/require-less#77]
When upgrading less to the latest version 2, I get this error when running r.js:

```
Error: TypeError: Cannot read property 'contents' of undefined
at Object.Parser.parse (C:\r\larsthorup\jsdevenv-require\node_modules\less\lib\less\parser\parser.js:109:20)
```

This seems to be related to this issue: https://github.com/less/less.js/issues/2278.

What are the plans for updating require-less to support less version 2?

**Comment by crazyjat** [comment]
Why does nothing work. I'm having the same issue. I don't want to have to install any node modules at all if I can help it. Why can't I just use the less.js file to compile? Why is the documentation on optimizing with r.js so incomplete?

**Comment by gaperton** [comment]
`npm install less@^1.7.5` works. 1.0.0 - doesn't

**Comment by crazyjat** [comment]
I need less > 2.2.0 for svg-gradient support. Would love for someone to update this project to properly support the newest version.

**Comment by gamtiq** [comment]
In https://github.com/gamtiq/require-less I updated less up to 2.5.x.
See also #67

**Comment by murrayju** [comment]
This seems to be critical for working in nodejs v6. Less 1.x depends on some old version of graceful-fs that is totally broken in node 6, and causes my r.js build to fail.

@guybedford Do you still maintain this? Do you plan to upgrade to less v2?

@gamtiq I tried your fork and got different errors... Have you tried yours with r.js builder on node 6?

**Comment by guybedford** [comment]
@murrayju yes this project is no longer maintained. If anyone would like to work on the update let me know.

**Comment by purtuga** [comment]
FYI: I tried @GerHobbelt fork and although it worked in the browser, it generated errors when used with r.js (build under node - 0.12 I think)

**Comment by gamtiq** [comment]
@murrayju I did not try my fork with r.js nor with node 6.

**Comment by Obooman** [comment]
`npm install @bracken/require-less@0.1.6`
