### ISSUE TITLE
Optimizer Ignore "less!somefile.less" without modification

### ISSUE THREAD

**Issue by crazyjat** [guybedford/require-less#81]
How can I run the r.js optimizer and have it ignore the "less!somefile.less" directives? I have a separate build process that compiles the less files down to a single css file. 

Also, without installing the nodejs less module globally I get errors that it can't find less. I am using a remote build machine and can't use a globally installed less nodejs module. Using a locally installed less module does not work. 

TypeError: Cannot read property 'contents' of undefined
In module tree:
    lib/main
      lib/less

Why does this have to be so hard? Please help.

**Comment by crazyjat** [comment]
I'd still like a way to ignore less files without modifying my source, but I found a work-around. It seems that less 2.x is just terrible and doesn't work. Downgrading to 1.7.5 works great now.  Terrible!

**Comment by Obooman** [comment]
less 2.0 issue, duplicated with #77
